steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Archive specific files and directories
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'tar --exclude=node_modules --exclude=logs --exclude=temp -czf nodeapp.tar.gz . && gsutil cp nodeapp.tar.gz gs://$PROJECT_ID-node-app-source/nodeapp-$SHORT_SHA.tar.gz']

# Substitute the $PROJECT_ID and $SHORT_SHA environment variables
substitutions:
  _PROJECT_ID: 'your-gcp-project-id'  # Replace with your GCP project ID
  _SHORT_SHA: 'short-sha'  # This is automatically replaced by Cloud Build with the short SHA of the commit
