steps:
  # Existing steps to create and upload the archive
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'tar -czf nodeapp.tar.gz --exclude=node_modules --exclude=.git .']
  
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'nodeapp.tar.gz', 'gs://ss-devops-408816-artifactbucket/latest-nodeapp.tar.gz']

  # Additional step to trigger a rolling restart of the instance group
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instance-groups', 'managed', 'rolling-restart', 'nodegroup', '--zone=us-west4']


  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instance-groups', 'managed', 'rolling-restart', 'nodegroup', '--zone=us-west4']

substitutions:
  _GCS_BUCKET: 'ss-devops-408816-artifactbucket'
