steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Run tests (optional)
 # - name: 'gcr.io/cloud-builders/npm'
 #   args: ['test']

  # Step 3: Deploy to Compute Engine instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'cd /nodeappGCE && git pull origin master && npm install && pm2 restart all']
