steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install-dependencies'
    args: ['sudo', 'npm', 'install']

  # Step 2: Configure Git Safe Directory
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'configure-git-safe-dir'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'sudo git config --global --add safe.directory /home/amalshibusocial/nodeappGCE']

  # Step 3: Pull Latest Code from Repository
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'pull-latest-code'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'cd /home/amalshibusocial/nodeappGCE && sudo git pull origin main']

  # Step 4: Install Node Dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'install-node-dependencies'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'cd /home/amalshibusocial/nodeappGCE && sudo npm install']

  # Step 5: Restart Application using PM2
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'restart-app-pm2'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'cd /home/amalshibusocial/nodeappGCE && sudo pm2 restart nodeappGCE || sudo pm2 start app.js --name nodeappGCE']

  # Step 6: Save PM2 Process List
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'save-pm2-process-list'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'sudo pm2 save']

  # Step 7: Set up PM2 Startup Script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'setup-pm2-startup-script'
    args: ['sudo', 'compute', 'ssh', 'nodebase', '--zone', 'us-west4-b', '--command', 'sudo pm2 startup systemd -u amalshibusocial --hp /home/amalshibusocial && sudo pm2 save']
