steps:
  # Step 1: Archive the application code excluding node_modules
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'tar --exclude=node_modules -czf nodeapp.tar.gz .']

  # Step 2: Upload the archive to Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'nodeapp.tar.gz', 'gs://$PROJECT_ID-node-app-source/nodeapp-$SHORT_SHA.tar.gz']

# Substitute the $PROJECT_ID and $SHORT_SHA environment variables
substitutions:
  _PROJECT_ID: 'your-gcp-project-id'  # Replace with your GCP project ID
  _SHORT_SHA: 'short-sha'  # This is automatically replaced by Cloud Build with the short SHA of the commit
